description: |
  用户账户相关接口
post:
  description: |
    新建一个账户,用户注册
  body:
    application/json:
      schema: |
        {
          "username":"test01",
          "password":"1234"
        }
  responses:
    200:
      body:
        application/json:
          schema: |
            {
              "code":"200",
              "message":"没问题"
            }
/authentication:
  post:
    is: [loginSecured]
    description: |
      账户登录
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "code": "200",
                "message": "登录成功",
                "data": {
                  "id": "1",
                  "username": "test01"
                }
              }
  delete:
    is: [secured]
    description: |
      用户登出
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "code":"200",
                "message":"成功",
                "data":{
                  "result":true
                }
              }
