description: |
  代码相关接口
post:
  description: |
    新建一个code模块
  body:
    application/json:
      schema: |
        {
          "title":"神牛写得牛逼代码",
          "content":"System.out.println('fsadfsad')",
          "description": "test"
        }
  responses:
    200:
      body:
        application/json:
          schema: |
            {
              "code":"200",
              "message": "成功"
            }
/{id}:
  /reply:
    post:
      description: |
        对一个代码评论
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "message": "成功"
                }
    delete:
      description: |
        删除一条评论
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "message": "成功"
                }
  /opposition:
    post:
      description: |
        对一个代码踩
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "message": "成功"
                }
    delete:
      description: |
        取消对一个代码的踩
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "message": "成功"
                }
  /awesome:
    post:
      description: |
        对一个代码点赞
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "message": "成功"
                }
    delete:
      description: |
        取消一个点赞
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "code":"200",
                  "message": "成功"
                }
  get:
    description: |
      通过id获取一个code模块
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "code":"200",
                "message":"成功",
                "data":{
                  "id":"1",
                  "title":"神牛写得牛逼代码",
                  "content":"System.out.println('fsadfsad')",
                  "description": "test",
                  "createTime":"2015-10-10 08:00:00",
                  "updateTime":"2015-10-10 08:00:00"
                }
              }
  put:
    description: |
      更新一个code 模块
      ~_~!!
    body:
      application/json:
        schema: |
          {
            "id":"1",
            "title":"博士",
            "content":"System.out.println('fsadfsad')",
            "description": "test",
            "createTime":"2015-10-10 08:00:00",
            "updateTime":"2015-10-10 08:00:00"
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "code":"200",
                "message":"成功",
                "data":{
                  "id":"1",
                  "title":"博士",
                  "content":"System.out.println('fsadfsad')",
                  "description": "test",
                  "createTime":"2015-10-10 08:00:00",
                  "updateTime":"2015-10-10 08:00:00"
                }
              }
  delete:
    description: |
      删除一个 code 模块
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "code":"200"
              }
